Repository olivia-ai/olivia, pull requests merged in 2020-05, with the labels that each got.

#108 added german as languange
  language/date/date.go
  language/date/rules.go
  language/math.go
  language/movies.go
  language/music.go
  language/reason.go
  locales/locales.go
  res/locales/de/intents.json
  res/locales/de/messages.json
  res/locales/de/modules.go
  res/locales/de/stopwords.txt
  res/locales/de/training.json
Labels: kind:enhancement, status:accepted

#110 Initial commit for the Italian translation
  language/math.go
  language/reason.go
  locales/locales.go
  res/datasets/countries.json
  res/locales/it/intents.json
  res/locales/it/messages.json
  res/locales/it/modules.go
  res/locales/it/stopwords.txt
  res/locales/it/training.json
Labels: kind:enhancement, status:accepted

#115 modules: created a jokes module, fixes #80
  modules/jokes.go
  res/locales/en/messages.json
  res/locales/en/modules.go
  res/locales/en/training.json
Labels: kind:module-enhancement, status:accepted

#120 Update the random module to support range, fixes #79
  language/random.go
  language/random_test.go
  modules/random.go
  res/locales/en/messages.json
  res/locales/en/training.json
Labels: kind:module-enhancement, status:discussion

#118 Turkish translations intents part completed.
  language/math.go
  language/music.go
  language/reason.go
  locales/locales.go
  res/datasets/countries.json
  res/locales/tr/intents.json
  res/locales/tr/messages.json
  res/locales/tr/modules.go
  res/locales/tr/stopwords.txt
  res/locales/tr/training.json
Labels: kind:enhancement, status:discussion
